# Environment specification for a sample notebook

name: pydata_example
dependencies:
  - python=3.6.4
  - jupyter=1.0.0
  - ipython=6.2.1
  - dask=0.17.0
  - python-graphviz=0.8.2
  - graphviz=2.38
  - cytoolz=0.9.0
